version: '2'
services:
  php:
    build: .
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - .:/var/www/html
    links:
     - db
  db:
    image: mysql:5.7
    volumes:
     - ./mysql:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=123
     - MYSQL_DATABASE=database

